### PR TITLE
Idempotency fixes

### PR DESCRIPTION
**Pull request by detjensrobert**
Unfortunately, `yum_plugin_versionlock` is still not idempotent on Centos 7. C8 and Debian are.

### CODE REVIEW

**Comment by ramereth** [comment]
@detjensrobert WAT, how is it still not working on EL7?

**Comment by detjensrobert** [comment]
[Update to yum-plugin-versionlock >= 0.3.0](https://trello.com/c/WcFyE6EK/2060-update-to-yum-plugin-versionlock-030)

**Comment by detjensrobert** [comment]
I'm investigating that currently.

**Comment by detjensrobert** [comment]
Found the issue. We lock two packages: `docker-ce` and `docker-ce-cli`. The regex to find what line to replace on a lock update is `/^[0-9]+:$PKGNAME-.+-.+\./`, which when filled in for docker-ce (`^[0-9]+:docker-ce-.+-.+\.`) also matches docker-ce-cli. Since remove duplicates is on for the resource, any subsequent matches are marked as duplicate and removed. The line for `-cli` is then immediately re-added by the `docker-ce-cli` lock resource.

I imagine there is a better regex to match the full package string, e.g. `/^\d+:$PKGNAME-\d.+-.+\./` as long as the version number always starts with a number.

**Comment by ramereth** [comment]
So yet another upstream fix you'll have to do? Nice catch on that. Regex are fun!

**Comment by detjensrobert** [comment]
Created an issue upstream: https://github.com/karnauskas/chef-yum-plugin-versionlock/issues/27

**Comment by detjensrobert** [comment]
Tested the new regex with my fork and that did indeed fix it.

**Comment by ramereth** [comment]
@detjensrobert please go ahead and temporarily point this and other PRs to that fix to ensure there aren't any other issues we missed.

**Comment by ramereth** [comment]
@detjensrobert so this isn't quite idempotent due to the fact that the `docker-ce` package uses a package epoch of `3:18.09.2`. However, for whatever reason, the `docker-ce-cli` package is `1:18.09.2`.

At this point, I recommend we add some helper method(s) to deal with this since it's messy to do in attributes. And actually, I'm not sure if we need/want the attributes anymore since I can't think of any system we set this version different than what we set. Perhaps that should just be a helper method directly calling the resource.

Let me know if this doesn't make sense.

**Comment by detjensrobert** [comment]
@ramereth Not sure I exactly follow. I confirm that this is still not idempotent, though. The correct epochs are set for the respective packages, so not sure what the problem is.

Are you suggesting hardcoding the version and release in the resources?

**Comment by ramereth** [comment]
@detjensrobert apologies for the confusion. I'm suggesting that we move the following attributes:

https://github.com/osuosl-cookbooks/osl-docker/blob/bf1a5ba82301db0da853497f7e1c76a0227b02ce/attributes/default.rb#L1-L16

To helper methods.

These methods need to use the following logic:
1. Have a central `osl_docker_version` method for the simple version (i.e. `18.09.2`)
2. Have methods which translate it to proper strings we need for the various platforms
3. On RHEL, the `docker-ce` package should have an epoch of `3` while the `docker-ce-cli` package should have an epoch of `1`
Does this help?

**Comment by detjensrobert** [comment]
Finally got the idempotency issue worked out. `yum_package` needs the package epoch to be specified to correctly match the installed version. I believe this is fixed in chef/chef#9847 / Chef 16. This shouldnt break anything, since the `docker_installation_package` only installs the `docker_ce` package and not `docker_ce_cli`.

**Review by ramereth — APPROVED** [review]
This should be a minor bump when merged.

**Comment by detjensrobert** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.12.0.  Have a nice day!

**Pull request merged**
