### PR TITLE
Update to latest upstream docker cookbook

### PR DESCRIPTION
**Pull request by ramereth**
Also update ChefSpec platforms and include Debian 9.

### CODE REVIEW

**Comment by doublej472** [comment]
@ramereth I got the missing test to go away by moving the `package` directive over:

```diff
diff --git a/recipes/default.rb b/recipes/default.rb
index 3e043cc..1058873 100644
--- a/recipes/default.rb
+++ b/recipes/default.rb
@@ -38,12 +38,13 @@ if node['platform_family'] == 'rhel' && node['kernel']['machine'] != 's390x'
   end
 end
 
-# Needed on Debian 9 to import the GPG key
-package 'dirmngr' do
-  only_if { node['platform_family'] == 'debian' && node['platform_version'].to_i >= 9 }
-end
-
 if node['platform_family'] == 'debian'
+  # Needed on Debian 9 to import the GPG key
+  package 'dirmngr' do
+    only_if { node['platform_version'].to_i >= 9 }
+    action :install
+  end
+
   include_recipe 'chef-apt-docker'
 
   apt_repository 'docker-main' do
```

**Comment by doublej472** [comment]
@ramereth All chefspec and serverspec tests pass, code looks good!
# LGTM!

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.1.0.  Have a nice day!

**Pull request merged**
